export const queryKeys = {
  stats: ['stats'] as const,
  projects: ['projects'] as const,
  project: (projectId: string) => ['project', projectId] as const,
  assets: (projectId: string, type: string) => ['assets', projectId, type] as const,
  assetsAll: (projectId: string, type: string) => ['assetsAll', projectId, type] as const,
  chapters: (projectId: string) => ['chapters', projectId] as const,
  chaptersAll: (projectId: string) => ['chaptersAll', projectId] as const,
  chapter: (chapterId: string) => ['chapter', chapterId] as const,
  characterStatesLatest: (projectId: string) => ['characterStates', projectId, 'latest'] as const,
  characterStatesChapter: (projectId: string, chapterId: string) =>
    ['characterStates', projectId, 'chapter', chapterId] as const,
  relationTypes: ['relationTypes'] as const,
  timeline: (projectId: string) => ['timeline', projectId] as const,
  llmProviders: ['llmProviders'] as const,
  llmTimeoutPolicy: ['llmTimeoutPolicy'] as const,
  prompts: (projectId: string) => ['prompts', projectId] as const,
  foreshadowings: (projectId: string) => ['foreshadowings', projectId] as const,
  kgNodes: (projectId: string) => ['kgNodes', projectId] as const,
  kgEdges: (projectId: string) => ['kgEdges', projectId] as const,
  dashboard: (projectId?: string) => ['dashboard', projectId ?? 'global'] as const,
}
